apiVersion: v1
kind: Service
metadata:
  name: web-app-backend
spec:
  type: ClusterIP
  selector:
    app: web-app-backend
  ports:
    - port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-frontend
spec:
  type: LoadBalancer
  selector:
    app: web-app-frontend
  ports:
    - port: 80
      targetPort: 80
